# Brownie configuration file
# https://eth-brownie.readthedocs.io/en/stable/config.html
# required external contracts
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.8.3
  - OpenZeppelin/openzeppelin-contracts-upgradeable@4.8.3

pytest:
    # these settings replace the defaults when running pytest
    default_contract_owner: true
    revert_traceback: true

compiler:
  #evm_version: "shanghai"
    solc:
        version: 0.8.17
        optimizer:
          enabled: true
          runs: 200
        remappings:
          - "@openzeppelin/contracts=../contracts/lib/OpenZeppelin/openzeppelin-contracts@4.8.3/contracts"
          - "@openzeppelin/contracts-upgradeable=../contracts/lib/OpenZeppelin/openzeppelin-contracts-upgradeable@4.8.3/contracts"

# automatically fetch contract sources from Etherscan
autofetch_sources: True

networks:
#  default: mainnet-fork
  mainnet-fork:
    cmd_settings:
      evm_version: "shanghai"
  holesky-fork:
    cmd_settings:
      default_balance: "10000 ether"
      unlock:
        - 0xC0c9E78BfC3996E8b68D872b29340816495D7e89  # ProxyAdmin owner address
      