# Brownie configuration file
# https://eth-brownie.readthedocs.io/en/stable/config.html
# required external contracts
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.8.3
  - OpenZeppelin/openzeppelin-contracts-upgradeable@4.8.3

pytest:
    # these settings replace the defaults when running pytest
    default_contract_owner: true
    revert_traceback: true

compiler:
  #evm_version: "shanghai"
    solc:
        version: 0.8.17
        optimizer:
          enabled: true
          runs: 200
        remappings:
          - "@openzeppelin/contracts=OpenZeppelin/openzeppelin-contracts@4.8.3/contracts"
          - "@openzeppelin/contracts-upgradeable=OpenZeppelin/openzeppelin-contracts-upgradeable@4.8.3/contracts"
          - "@celer-network/contracts=./lib/celer-network/sgn-v2-contracts-main/contracts"

# automatically fetch contract sources from Etherscan
autofetch_sources: True
networks:
#  default: mainnet-fork
  mainnet-public-fork:
    cmd_settings:
      default_balance: "1000000000000 ether"
      unlock:
        - 0x899c284A89E113056a72dC9ade5b60E80DD3c94f  # Vault deployer
        - 0x9251fd3D79522bB2243a58FFf1dB43E25A495aaB  # Vault default Admin
        - 0xC9dA980fFABbE2bbe15d4734FDae5761B86b5Fc3  # ProxyAdmin owner
        - 0xbFdDf5e269C74157b157c7DaC5E416d44afB790d  # FBTCProxy owner
  mainnet-fork:
    cmd_settings:
      #    evm_version: "shanghai"
