# Brownie configuration file
# https://eth-brownie.readthedocs.io/en/stable/config.html
# required external contracts
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.8.3
  - OpenZeppelin/openzeppelin-contracts-upgradeable@4.8.3

pytest:
    # these settings replace the defaults when running pytest
    default_contract_owner: true
    revert_traceback: true

compiler:
  #evm_version: "shanghai"
    solc:
        version: 0.8.17
        optimizer:
          enabled: true
          runs: 200
        remappings:
          - "@openzeppelin/contracts=OpenZeppelin/openzeppelin-contracts@4.8.3/contracts"
          - "@openzeppelin/contracts-upgradeable=OpenZeppelin/openzeppelin-contracts-upgradeable@4.8.3/contracts"
          - "@celer-network/contracts=./lib/celer-network/sgn-v2-contracts-main/contracts"
          - "@chainlink-ccip=./lib/chainlink-network/v2.14.0-ccip1.5.1/contracts/src/v0.8/ccip"

# automatically fetch contract sources from Etherscan
autofetch_sources: True
networks:
#  default: mainnet-fork
  mainnet-fork:
    cmd_settings:
      #    evm_version: "shanghai"
  merlin-mainnet-fork:
    cmd_settings:
      default_balance: "1000000000000 ether"
      unlock:
        - 0x9251fd3D79522bB2243a58FFf1dB43E25A495aaB  # ProxyAdmin owner address
        - 0x9251fd3D79522bB2243a58FFf1dB43E25A495aaB  # Vault default admin address